### ISSUE TITLE
Are there any plans to make UnnecessaryNamespaceUsageSniff fixable?

### ISSUE THREAD

**Issue by orlangur** [mayflower/mo4-coding-standard#11]
https://github.com/mayflower/mo4-coding-standard/blob/master/Sniffs/Formatting/UnnecessaryNamespaceUsageSniff.php

Such transformation would be safe, isn't it? (Or at least safer than more agressive https://github.com/QafooLabs/php-refactoring-browser#optimize-use-statements)

**Comment by xalopp** [comment]
@orlangur currently there is no plan to make "UnnecessaryNamespaceUsageSniff" fixable.
Although, this feature should be quite easy to implement, because all the data for proper fixing are available. So, feel free to implement it and do a pull request :-)

I think this type of transformation should be 99% safe. The 1% left is due to a "todo test" in line 111 introduced by @mmoll. @mmoll could you point out what type of test is missing?

**Comment by mmoll** [comment]
The line was already there and only got reformatted in b9926e5c to conform to the PHPCSCS itself. The comment was inserted by @xalopp in 98087cb1.

**Comment by orlangur** [comment]
> Although, this feature should be quite easy to implement, because all the data for proper fixing are available. 

Thanks for pointing this out, will try.
