### ISSUE TITLE
have logical operators at the end of multiline statements

### ISSUE THREAD

**Issue by mmoll** [mayflower/mo4-coding-standard#22]
I propose the following coding standard:

``` php
if (foo === true &&
    bar === false)
[...]
```

as opposed to:

``` php
if (foo === true
    && bar === false)
[...]
```

because I know that the condition will continue when there's an operator at the end.

@xalopp @ritters @andythedandy @periklis @calbrecht @elger @danielhallmann please discuss/vote.

**Comment by ritters** [comment]
+1

**Comment by xalopp** [comment]
I think that for multi line condition, the closing parenthesis should be on a new line, directly followed by the opening curly bracket.

    if ($a === true
        && $b === 'yes'
    ) {
    ...
    }

I understand @mmoll argument, but on the other side, putting the logical operator in the beginning of the line, it makes perfectly clear which operation is applied on the line, and removing the condition just requires to delete on line, and not deleting and editing the line before.

Are there any coding other coding standards addressing this issue? This might me useful for  to form an opinion.

**Comment by mmoll** [comment]
I can only say that the PHPCS-CS requires the opposite of my proposal. With curly braces included I'd even go for:
```php
if ($a === true &&
    $b === 'yes')
    {
        ...
    }
```

**Comment by xalopp** [comment]
Actually this comes from [PEAR Coding Standards Control Structures](http://pear.php.net/manual/en/standards.control.php) Section "Split long if statements onto several lines"

With following argument.

`Keeping the operators at the beginning of the line has two advantages: It is trivial to comment out a particular line during development while keeping syntactically correct code (except of course the first line). Further is the logic kept at the front where it's not forgotten. Scanning such conditions is very easy since they are aligned below each other.`

=> my vote: :-1:

**Comment by mmoll** [comment]
I'm outraged, but won't argue against PEAR.

**Comment by mmoll** [comment]
I was outrageously overvoted.

**Comment by johnhunt** [comment]
@mmoll don't let it get you down. I too think it's easier to read and nicer looking at the end of the line

**Comment by mmoll** [comment]
Thanks @johnhunt for the encouragement, but adhering to existing standards and the consent of the majority of the people creating MO4 is more important, even if I personally dislike it. 🍦
