### ISSUE TITLE
do care about spaces around concatenation (.)

### ISSUE THREAD

**Issue by calbrecht** [mayflower/mo4-coding-standard#23]
at this moment mo4 does not care whether there are spaces around concatenation operator (.) -- but it should.
```php
$a = $b.$c;
$a = $b . $c;
```
are both valid.

**Comment by xalopp** [comment]
@calbrecht please have a look at the "Structure" Section of the [Symfony Coding Standards]
(http://symfony.com/doc/current/contributing/code/standards.htmll#structure).

```Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator;```

I think they actually mean that the concatenation operator must not be surrounded by spaces.

Since MO4 extends the Symfony Coding Standards, I may not implement any mutually contradictory rules.

Als alternative, use

    $a = "{$b}{$c}";

or

    $a = sprintf('%s%s', $a, $b);

**Comment by calbrecht** [comment]
Yeah well, so it's symfonys rules fault
