### ISSUE TITLE
Consider creating a check (and fixer) for having all return types including "@return void" in phpDoc-block

### ISSUE THREAD

**Issue by SebTM** [mayflower/mo4-coding-standard#81]
These annotations are also used for tools like phpdox and since PHP7 as there is a real type-safty and difference of returning void/null or something else I would like to have it for every function/method.

I see a benefit for automatic processing these annotation by code-quality-tools or documentation generators.

**Comment by Ma27** [comment]
Although your explanation seems fairly reasonable to me (and we could even think about making this a new default), I'm not entirely convinced. Shouldn't API doc generation tools derive type signatures from type hints in PHP7 (especially when setting `strict_types=1`)?

In the end I'm quite skeptical regarding docblocks in PHP7 (unless they provide actual descriptions for parameters/method/return value).

**Comment by mmoll** [comment]
Is this https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintstypehintdeclaration- or something different?

**Comment by Ma27** [comment]
After skimming through the linked ruleset it seems quite reasonable to me.

@SebTM what do you think about this?

**Comment by SebTM** [comment]
Yeah looks also good for me - we should give it a try 👍

**Comment by mmoll** [comment]
I think we should open up a general discussion about pulling in Slevomat as dependency then.

**Comment by mmoll** [comment]
@SebTM While it's not 100% as specified here, please check if the current master with `SlevomatCodingStandard.TypeHints.TypeHintDeclaration` does cover your need.

**Comment by xalopp** [comment]
https://symfony.com/doc/current/contributing/code/standards.html#documentation
says 

> Omit the @return tag if the method does not return anything;

On the other side, the example on the same page shows a `@return bool|void`

MO4 v2.1.2 accepts:

```
<?php
  
namespace B;

class A
{
    /**
     * Empty function
     *
     * @return void
     */
    public function t(): void
    {
    }
}
```

and

```
<?php
  
namespace B;

class A
{
    /**
     * Empty function
     */
    public function t(): void
    {
    }
}
```

For me that's fine. But requiring the '@return void' would violating the Symfony Coding Standard.

**Comment by SebTM** [comment]
Hmm if the Symfony-Coding-Standard says "don't make this annotation for void only" (so bool|void is a special case because not only void) I would suggest to then implement a sniff and fixer which checks for pure "@return void" and removes them to have a project-standard and get rid of mixing it up.

**Comment by Ma27** [comment]
I agree with @SebTM here, we should get rid of these inconsistencies.
Does anybody know if there's an existing fixer that solves this issue? Otherwise I'd give it a try in the next days :smile:

**Comment by mmoll** [comment]
As we're more or less depending on `SlevomatCodingStandard.TypeHints`, please have a look there.

**Comment by Ma27** [comment]
The relevant parts in the code can be found here: https://github.com/slevomat/coding-standard/blob/31357d1b51459da995e4a4cc105c2a981a4a10b5/SlevomatCodingStandard/Sniffs/TypeHints/TypeHintDeclarationSniff.php#L400-L452

It allows `@return void` if the deprecated flag `enableVoidTypeHint` is true and throws errors if it's not present. However it doesn't cover the case where `@return void` exists, but should be removed.

Another feature I found was the flag `enableEachParameterAndReturnInspection` which isn't exactly what we want I guess. It removes **all** docblock annotations which don't provide additional information (such as a descriptions for `@param`) since all types can be expressed with native PHP.

So e.g. in `integrationtests/testfile.php` the `@return string` of `deprecatedMethod` would be superfluous as it doesn't provide additional information.

IIRC we agreed on keeping all tags except `@return void` (correct me if I'm wrong).

Both approaches seem to be symfony-CS compliant (`Add PHPDoc blocks for all classes, methods, and functions (though you may be asked to remove PHPDoc that do not add value);`), so we can either use this flag (which is a breaking change for us and therefore needs to be in v3) or implement the check ourselves (I'd talk to the Slevomat folks first to see if it makes sense to enhance their sniff).

**Comment by mmoll** [comment]
In the meanwhile the PHP world settled to omit the return tag, when void is returned, so I'd close this.
